### ISSUE TITLE
Coordinates for Region Objects

### ISSUE THREAD

**Issue by jamesholland-uk** [PaloAltoNetworks/terraform-provider-sase#2]
## Describe the bug
The web GUI lets you use lat/long coordinates for a Region to multiple decimal places:
<img width="1250" alt="Screenshot 2023-03-20 at 12 56 32" src="https://user-images.githubusercontent.com/6574404/226572474-a4d14ac4-8222-4f14-a1ee-573269ccce98.png">
<img width="702" alt="Screenshot 2023-03-20 at 12 56 45" src="https://user-images.githubusercontent.com/6574404/226572542-be534a84-1451-496e-9995-559816994bf5.png">
The provider only let's you use one decimal place (example 51.5) and when you get to two decimal places or more (example 51.51) the error below is receieved:
<img width="1039" alt="Screenshot 2023-03-20 at 12 57 42" src="https://user-images.githubusercontent.com/6574404/226572695-b9a36c55-bdfd-4c96-9772-278b60cb36cf.png">

## Expected behavior
Provider should allow input of the same format of number as the web GUI and underlying PAN-OS

## Current behavior
Provider errors if more than one decimal place number is used

## Steps to reproduce
```
resource "sase_objects_regions" "test_terraform_01" {
  folder = "Shared"
  name   = "test-region-01-terraform-london"
  geo_location = {
    latitude  = 51.500152
    longitude = -0.126236
  }
}
```

## Screenshots
See above

## Your Environment
- Version used: No provider version yet, tested with up-to-date `git pull` on 20 March 2023
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Terraform 1.3.8
- Operating System and version (desktop or mobile): MacOS Ventura 13.2.1
- Link to your project: https://github.com/jamesholland-uk/playground/tree/main/sase-terraform

**Comment by shinmog** [comment]
This looks to have been a SDK bug, which was fixed in yesterday's 1.2 release:

hashicorp/terraform-plugin-framework#648

I'll update the dependencies for the provider and this should be fixed.
