### ISSUE TITLE
Include acceptable parameters within resources. This is one example, but multiple resources need such enhancements to the docs.

### ISSUE THREAD

**Issue by ancoleman** [PaloAltoNetworks/terraform-provider-sase#7]
## Documentation link
https://github.com/PaloAltoNetworks/terraform-provider-sase/blob/main/docs/resources/ike_crypto_profiles.md#required

## Describe the problem
Docs are missing acceptable parameters, only includes types. The example link provided was just one such resource where acceptable parameters is missing.

## Suggested fix

Example acceptable parameters for ike_crypto_profiles:
- dh_group: [group1, group2, group5, group14, group19, group20]
- encryption: [des, 3des, aes-128-cbc, aes-192-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm]
- hash: [md5, sha1, sha256, sha384, sha512]

**Comment by shinmog** [comment]
It should be, but isn't...  I just updated all docs to also include `MarkdownDescription` just in case that was needed to include the validator docstrings, but it still isn't being added...  So I suspect that this is a bug with the HashiCorp docs generation tool.  I've reached out to my contact there to get an answer.
